"""phase1_complete_schema

Revision ID: 0fbfab7c074a
Revises: 
Create Date: 2026-03-15 20:06:18.038971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fbfab7c074a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_wer_samples_accent'), table_name='wer_audio_samples', schema='linguamentor')
    op.drop_table('wer_audio_samples', schema='linguamentor')
    op.drop_index(op.f('idx_cal_essays_exam_type'), table_name='calibration_essays', schema='linguamentor')
    op.drop_index(op.f('idx_cal_essays_grading_complete'), table_name='calibration_essays', schema='linguamentor')
    op.drop_table('calibration_essays', schema='linguamentor')
    op.drop_table('calibration_baseline', schema='linguamentor')
    op.drop_index(op.f('idx_cal_runs_exam_type'), table_name='calibration_runs', schema='linguamentor')
    op.drop_index(op.f('idx_cal_runs_passed'), table_name='calibration_runs', schema='linguamentor', postgresql_where='(passed_threshold = true)')
    op.drop_table('calibration_runs', schema='linguamentor')
    op.drop_index(op.f('idx_wer_runs_passed'), table_name='wer_validation_runs', schema='linguamentor', postgresql_where='(passed_threshold = true)')
    op.drop_table('wer_validation_runs', schema='linguamentor')
    op.drop_table('wer_baseline', schema='linguamentor')
    op.drop_index(op.f('idx_cal_human_scores_essay_id'), table_name='calibration_human_scores', schema='linguamentor')
    op.drop_index(op.f('idx_cal_human_scores_unique'), table_name='calibration_human_scores', schema='linguamentor')
    op.drop_table('calibration_human_scores', schema='linguamentor')
    op.drop_index(op.f('idx_cal_ai_scores_essay_id'), table_name='calibration_ai_scores', schema='linguamentor')
    op.drop_index(op.f('idx_cal_ai_scores_run_id'), table_name='calibration_ai_scores', schema='linguamentor')
    op.drop_table('calibration_ai_scores', schema='linguamentor')
    op.drop_index(op.f('idx_wer_results_run_id'), table_name='wer_transcription_results', schema='linguamentor')
    op.drop_index(op.f('idx_wer_results_sample_id'), table_name='wer_transcription_results', schema='linguamentor')
    op.drop_table('wer_transcription_results', schema='linguamentor')
    op.add_column('ai_model_runs', sa.Column('calibration_sample_count', sa.Integer(), nullable=True), schema='linguamentor')
    op.alter_column('ai_model_runs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_ai_model_runs_task_time'), table_name='ai_model_runs', schema='linguamentor')
    op.drop_index(op.f('idx_ai_model_runs_user_ref'), table_name='ai_model_runs', schema='linguamentor')
    op.add_column('daily_sessions', sa.Column('srs_priority_score', sa.Numeric(precision=5, scale=4), nullable=True), schema='linguamentor')
    op.alter_column('daily_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_constraint(op.f('daily_sessions_user_id_session_date_key'), 'daily_sessions', schema='linguamentor', type_='unique')
    op.drop_index(op.f('idx_daily_sessions_user_date'), table_name='daily_sessions', schema='linguamentor')
    op.create_unique_constraint('uq_daily_sessions_user_date', 'daily_sessions', ['user_id', 'session_date'], schema='linguamentor')
    op.alter_column('exam_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_exam_attempts_user_id'), table_name='exam_attempts', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('exam_sections', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_exam_sections_attempt'), table_name='exam_sections', schema='linguamentor')
    op.add_column('learner_profiles', sa.Column('placement_completed_at', sa.DateTime(timezone=True), nullable=True), schema='linguamentor')
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.alter_column('readiness_snapshots', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_readiness_snapshots_user_time'), table_name='readiness_snapshots', schema='linguamentor')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_refresh_tokens_hash'), table_name='refresh_tokens', schema='linguamentor', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens', schema='linguamentor')
    op.alter_column('score_appeals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_score_appeals_user_id'), table_name='score_appeals', schema='linguamentor')
    op.drop_constraint(op.f('score_appeals_speaking_session_id_key'), 'score_appeals', schema='linguamentor', type_='unique')
    op.drop_constraint(op.f('score_appeals_writing_session_id_key'), 'score_appeals', schema='linguamentor', type_='unique')
    op.create_unique_constraint('uq_appeals_speaking_session', 'score_appeals', ['speaking_session_id'], schema='linguamentor')
    op.create_unique_constraint('uq_appeals_writing_session', 'score_appeals', ['writing_session_id'], schema='linguamentor')
    op.add_column('share_events', sa.Column('delta', sa.Numeric(precision=4, scale=2), nullable=True), schema='linguamentor')
    op.alter_column('share_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_share_events_user_id'), table_name='share_events', schema='linguamentor')
    op.drop_column('share_events', 'improvement_delta', schema='linguamentor')
    op.alter_column('skill_vectors', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.alter_column('speaking_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_speaking_sessions_user_id'), table_name='speaking_sessions', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_users_email'), table_name='users', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.add_column('writing_sessions', sa.Column('calibration_sample_count', sa.Integer(), nullable=True), schema='linguamentor')
    op.alter_column('writing_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_writing_sessions_status'), table_name='writing_sessions', schema='linguamentor', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying])::text[]))")
    op.drop_index(op.f('idx_writing_sessions_user_id'), table_name='writing_sessions', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_writing_sessions_user_id'), 'writing_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_writing_sessions_status'), 'writing_sessions', ['status'], unique=False, schema='linguamentor', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying])::text[]))")
    op.alter_column('writing_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('writing_sessions', 'calibration_sample_count', schema='linguamentor')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_speaking_sessions_user_id'), 'speaking_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('speaking_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.alter_column('skill_vectors', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.add_column('share_events', sa.Column('improvement_delta', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True), schema='linguamentor')
    op.create_index(op.f('idx_share_events_user_id'), 'share_events', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('share_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('share_events', 'delta', schema='linguamentor')
    op.drop_constraint('uq_appeals_writing_session', 'score_appeals', schema='linguamentor', type_='unique')
    op.drop_constraint('uq_appeals_speaking_session', 'score_appeals', schema='linguamentor', type_='unique')
    op.create_unique_constraint(op.f('score_appeals_writing_session_id_key'), 'score_appeals', ['writing_session_id'], schema='linguamentor', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('score_appeals_speaking_session_id_key'), 'score_appeals', ['speaking_session_id'], schema='linguamentor', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_score_appeals_user_id'), 'score_appeals', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('score_appeals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_refresh_tokens_hash'), 'refresh_tokens', ['token_hash'], unique=False, schema='linguamentor', postgresql_where='(revoked_at IS NULL)')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_readiness_snapshots_user_time'), 'readiness_snapshots', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('readiness_snapshots', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('learner_profiles', 'placement_completed_at', schema='linguamentor')
    op.create_index(op.f('idx_exam_sections_attempt'), 'exam_sections', ['exam_attempt_id'], unique=False, schema='linguamentor')
    op.alter_column('exam_sections', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_exam_attempts_user_id'), 'exam_attempts', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('exam_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_constraint('uq_daily_sessions_user_date', 'daily_sessions', schema='linguamentor', type_='unique')
    op.create_index(op.f('idx_daily_sessions_user_date'), 'daily_sessions', ['user_id', sa.literal_column('session_date DESC')], unique=False, schema='linguamentor')
    op.create_unique_constraint(op.f('daily_sessions_user_id_session_date_key'), 'daily_sessions', ['user_id', 'session_date'], schema='linguamentor', postgresql_nulls_not_distinct=False)
    op.alter_column('daily_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('daily_sessions', 'srs_priority_score', schema='linguamentor')
    op.create_index(op.f('idx_ai_model_runs_user_ref'), 'ai_model_runs', ['user_reference_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_ai_model_runs_task_time'), 'ai_model_runs', ['task_type', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('ai_model_runs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('ai_model_runs', 'calibration_sample_count', schema='linguamentor')
    op.create_table('wer_transcription_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sample_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hypothesis_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wer', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('substitutions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('insertions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('deletions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transcribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['linguamentor.wer_validation_runs.id'], name=op.f('wer_transcription_results_run_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['linguamentor.wer_audio_samples.id'], name=op.f('wer_transcription_results_sample_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wer_transcription_results_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_wer_results_sample_id'), 'wer_transcription_results', ['sample_id'], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_wer_results_run_id'), 'wer_transcription_results', ['run_id'], unique=False, schema='linguamentor')
    op.create_table('calibration_ai_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('essay_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score_task_response', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('score_coherence_cohesion', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('score_lexical_resource', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('score_grammatical_range', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('score_overall', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prompt_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('score_coherence_cohesion >= 0::numeric AND score_coherence_cohesion <= 9::numeric', name=op.f('calibration_ai_scores_score_coherence_cohesion_check')),
    sa.CheckConstraint('score_grammatical_range >= 0::numeric AND score_grammatical_range <= 9::numeric', name=op.f('calibration_ai_scores_score_grammatical_range_check')),
    sa.CheckConstraint('score_lexical_resource >= 0::numeric AND score_lexical_resource <= 9::numeric', name=op.f('calibration_ai_scores_score_lexical_resource_check')),
    sa.CheckConstraint('score_overall >= 0::numeric AND score_overall <= 9::numeric', name=op.f('calibration_ai_scores_score_overall_check')),
    sa.CheckConstraint('score_task_response >= 0::numeric AND score_task_response <= 9::numeric', name=op.f('calibration_ai_scores_score_task_response_check')),
    sa.ForeignKeyConstraint(['essay_id'], ['linguamentor.calibration_essays.id'], name=op.f('calibration_ai_scores_essay_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('calibration_ai_scores_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_cal_ai_scores_run_id'), 'calibration_ai_scores', ['run_id'], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_cal_ai_scores_essay_id'), 'calibration_ai_scores', ['essay_id'], unique=False, schema='linguamentor')
    op.create_table('calibration_human_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('essay_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('examiner_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score_task_response', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('score_coherence_cohesion', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('score_lexical_resource', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('score_grammatical_range', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('score_overall', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('is_adjudicating', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('grader_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('score_coherence_cohesion >= 0::numeric AND score_coherence_cohesion <= 9::numeric', name=op.f('calibration_human_scores_score_coherence_cohesion_check')),
    sa.CheckConstraint('score_grammatical_range >= 0::numeric AND score_grammatical_range <= 9::numeric', name=op.f('calibration_human_scores_score_grammatical_range_check')),
    sa.CheckConstraint('score_lexical_resource >= 0::numeric AND score_lexical_resource <= 9::numeric', name=op.f('calibration_human_scores_score_lexical_resource_check')),
    sa.CheckConstraint('score_overall >= 0::numeric AND score_overall <= 9::numeric', name=op.f('calibration_human_scores_score_overall_check')),
    sa.CheckConstraint('score_task_response >= 0::numeric AND score_task_response <= 9::numeric', name=op.f('calibration_human_scores_score_task_response_check')),
    sa.ForeignKeyConstraint(['essay_id'], ['linguamentor.calibration_essays.id'], name=op.f('calibration_human_scores_essay_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('calibration_human_scores_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_cal_human_scores_unique'), 'calibration_human_scores', ['essay_id', 'examiner_id'], unique=True, schema='linguamentor')
    op.create_index(op.f('idx_cal_human_scores_essay_id'), 'calibration_human_scores', ['essay_id'], unique=False, schema='linguamentor')
    op.create_table('wer_baseline',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('validation_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('wer_en_us', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('wer_en_gb', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('wer_fr_fr', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('wer_fr_ca', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('clips_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asr_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['linguamentor.wer_validation_runs.id'], name=op.f('wer_baseline_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wer_baseline_pkey')),
    sa.UniqueConstraint('validation_version', name=op.f('wer_baseline_validation_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='linguamentor'
    )
    op.create_table('wer_validation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('run_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('asr_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('accent_targets', postgresql.ARRAY(sa.VARCHAR(length=10)), autoincrement=False, nullable=False),
    sa.Column('clips_scored', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('clips_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wer_en_us', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('wer_en_gb', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('wer_fr_fr', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('wer_fr_ca', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('passed_threshold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('wer_validation_runs_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_wer_runs_passed'), 'wer_validation_runs', ['passed_threshold'], unique=False, schema='linguamentor', postgresql_where='(passed_threshold = true)')
    op.create_table('calibration_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('run_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('essays_scored', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('pearson_task_response', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('pearson_coherence_cohesion', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('pearson_lexical_resource', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('pearson_grammatical_range', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('pearson_overall', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('passed_threshold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('prompt_config_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("exam_type::text = ANY (ARRAY['ielts_academic'::character varying, 'ielts_general'::character varying, 'toefl_ibt'::character varying, 'delf_b1'::character varying, 'delf_b2'::character varying]::text[])", name=op.f('calibration_runs_exam_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('calibration_runs_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_cal_runs_passed'), 'calibration_runs', ['passed_threshold'], unique=False, schema='linguamentor', postgresql_where='(passed_threshold = true)')
    op.create_index(op.f('idx_cal_runs_exam_type'), 'calibration_runs', ['exam_type'], unique=False, schema='linguamentor')
    op.create_table('calibration_baseline',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('calibration_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pearson_overall', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=False),
    sa.Column('pearson_task_response', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=False),
    sa.Column('pearson_coherence_cohesion', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=False),
    sa.Column('pearson_lexical_resource', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=False),
    sa.Column('pearson_grammatical_range', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=False),
    sa.Column('essays_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['linguamentor.calibration_runs.id'], name=op.f('calibration_baseline_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calibration_baseline_pkey')),
    sa.UniqueConstraint('calibration_version', name=op.f('calibration_baseline_calibration_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='linguamentor'
    )
    op.create_table('calibration_essays',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('task_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('essay_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('approximate_band', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grading_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("exam_type::text = ANY (ARRAY['ielts_academic'::character varying, 'ielts_general'::character varying, 'toefl_ibt'::character varying, 'delf_b1'::character varying, 'delf_b2'::character varying]::text[])", name=op.f('calibration_essays_exam_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('calibration_essays_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_cal_essays_grading_complete'), 'calibration_essays', ['grading_complete'], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_cal_essays_exam_type'), 'calibration_essays', ['exam_type'], unique=False, schema='linguamentor')
    op.create_table('wer_audio_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('accent_target', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('audio_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('reference_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('sample_rate_hz', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channels', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("accent_target::text = ANY (ARRAY['en-US'::character varying, 'en-GB'::character varying, 'fr-FR'::character varying, 'fr-CA'::character varying]::text[])", name=op.f('wer_audio_samples_accent_target_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('wer_audio_samples_pkey')),
    schema='linguamentor'
    )
    op.create_index(op.f('idx_wer_samples_accent'), 'wer_audio_samples', ['accent_target'], unique=False, schema='linguamentor')
    # ### end Alembic commands ###
