"""add task_prompt to writing_sessions

Revision ID: 8b69dfa93bb2
Revises: f095a2fc39eb
Create Date: 2026-03-19 10:14:23.651785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b69dfa93bb2'
down_revision: Union[str, Sequence[str], None] = 'f095a2fc39eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_runs', sa.Column('calibration_sample_count', sa.Integer(), nullable=True), schema='linguamentor')
    op.alter_column('ai_model_runs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_ai_model_runs_task_time'), table_name='ai_model_runs', schema='linguamentor')
    op.drop_index(op.f('idx_amr_calibration_version_created'), table_name='ai_model_runs', schema='linguamentor', postgresql_where='(calibration_version IS NOT NULL)')
    op.drop_index(op.f('idx_amr_created_brin'), table_name='ai_model_runs', schema='linguamentor', postgresql_with={'pages_per_range': '128'}, postgresql_using='brin')
    op.drop_index(op.f('idx_amr_model_name_created'), table_name='ai_model_runs', schema='linguamentor')
    op.drop_index(op.f('idx_amr_provider_task_created'), table_name='ai_model_runs', schema='linguamentor', postgresql_where='(provider_name IS NOT NULL)')
    op.drop_index(op.f('idx_amr_user_ref_task_created'), table_name='ai_model_runs', schema='linguamentor', postgresql_where='(user_reference_id IS NOT NULL)')
    op.add_column('daily_sessions', sa.Column('srs_priority_score', sa.Numeric(precision=5, scale=4), nullable=True), schema='linguamentor')
    op.alter_column('daily_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_constraint(op.f('daily_sessions_user_id_session_date_key'), 'daily_sessions', schema='linguamentor', type_='unique')
    op.drop_index(op.f('idx_daily_sessions_user_date'), table_name='daily_sessions', schema='linguamentor')
    op.drop_index(op.f('idx_ds_session_date_completed'), table_name='daily_sessions', schema='linguamentor', postgresql_where='(completed = false)')
    op.create_unique_constraint('uq_daily_sessions_user_date', 'daily_sessions', ['user_id', 'session_date'], schema='linguamentor')
    op.alter_column('exam_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_exam_attempts_user_id'), table_name='exam_attempts', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('exam_sections', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_exam_sections_attempt'), table_name='exam_sections', schema='linguamentor')
    op.add_column('learner_profiles', sa.Column('placement_completed_at', sa.DateTime(timezone=True), nullable=True), schema='linguamentor')
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_lp_accent_target'), table_name='learner_profiles', schema='linguamentor')
    op.drop_index(op.f('idx_lp_cefr_writing_user'), table_name='learner_profiles', schema='linguamentor', postgresql_where='(cefr_writing IS NOT NULL)')
    op.drop_index(op.f('idx_lp_target_exam'), table_name='learner_profiles', schema='linguamentor', postgresql_where='(target_exam IS NOT NULL)')
    op.drop_index(op.f('idx_lp_target_language'), table_name='learner_profiles', schema='linguamentor')
    op.alter_column('readiness_snapshots', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_readiness_snapshots_user_time'), table_name='readiness_snapshots', schema='linguamentor')
    op.drop_index(op.f('idx_rs_created_brin'), table_name='readiness_snapshots', schema='linguamentor', postgresql_with={'pages_per_range': '64'}, postgresql_using='brin')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_refresh_tokens_hash'), table_name='refresh_tokens', schema='linguamentor', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens', schema='linguamentor')
    op.alter_column('score_appeals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_appeals_status_created'), table_name='score_appeals', schema='linguamentor', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'escalated'::character varying])::text[]))")
    op.drop_index(op.f('idx_score_appeals_user_id'), table_name='score_appeals', schema='linguamentor')
    op.drop_constraint(op.f('score_appeals_speaking_session_id_key'), 'score_appeals', schema='linguamentor', type_='unique')
    op.drop_constraint(op.f('score_appeals_writing_session_id_key'), 'score_appeals', schema='linguamentor', type_='unique')
    op.create_unique_constraint('uq_appeals_speaking_session', 'score_appeals', ['speaking_session_id'], schema='linguamentor')
    op.create_unique_constraint('uq_appeals_writing_session', 'score_appeals', ['writing_session_id'], schema='linguamentor')
    op.add_column('share_events', sa.Column('delta', sa.Numeric(precision=4, scale=2), nullable=True), schema='linguamentor')
    op.alter_column('share_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_share_events_user_id'), table_name='share_events', schema='linguamentor')
    op.drop_column('share_events', 'improvement_delta', schema='linguamentor')
    op.alter_column('skill_vectors', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.alter_column('speaking_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_speaking_sessions_user_id'), table_name='speaking_sessions', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_users_email'), table_name='users', schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.add_column('writing_sessions', sa.Column('task_prompt', sa.Text(), nullable=True), schema='linguamentor')
    op.add_column('writing_sessions', sa.Column('calibration_sample_count', sa.Integer(), nullable=True), schema='linguamentor')
    op.alter_column('writing_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='linguamentor')
    op.drop_index(op.f('idx_ws_ai_model_run_id'), table_name='writing_sessions', schema='linguamentor', postgresql_where='(ai_model_run_id IS NOT NULL)')
    op.drop_index(op.f('idx_ws_pending_created'), table_name='writing_sessions', schema='linguamentor', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying])::text[]))")
    op.drop_index(op.f('idx_ws_user_status_created'), table_name='writing_sessions', schema='linguamentor', postgresql_where='(deleted_at IS NULL)', postgresql_include=['status', 'score_overall', 'exam_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_ws_user_status_created'), 'writing_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)', postgresql_include=['status', 'score_overall', 'exam_type'])
    op.create_index(op.f('idx_ws_pending_created'), 'writing_sessions', ['created_at'], unique=False, schema='linguamentor', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying])::text[]))")
    op.create_index(op.f('idx_ws_ai_model_run_id'), 'writing_sessions', ['ai_model_run_id'], unique=False, schema='linguamentor', postgresql_where='(ai_model_run_id IS NOT NULL)')
    op.alter_column('writing_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('writing_sessions', 'calibration_sample_count', schema='linguamentor')
    op.drop_column('writing_sessions', 'task_prompt', schema='linguamentor')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_speaking_sessions_user_id'), 'speaking_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('speaking_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.alter_column('skill_vectors', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.add_column('share_events', sa.Column('improvement_delta', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True), schema='linguamentor')
    op.create_index(op.f('idx_share_events_user_id'), 'share_events', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('share_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('share_events', 'delta', schema='linguamentor')
    op.drop_constraint('uq_appeals_writing_session', 'score_appeals', schema='linguamentor', type_='unique')
    op.drop_constraint('uq_appeals_speaking_session', 'score_appeals', schema='linguamentor', type_='unique')
    op.create_unique_constraint(op.f('score_appeals_writing_session_id_key'), 'score_appeals', ['writing_session_id'], schema='linguamentor', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('score_appeals_speaking_session_id_key'), 'score_appeals', ['speaking_session_id'], schema='linguamentor', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_score_appeals_user_id'), 'score_appeals', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_appeals_status_created'), 'score_appeals', ['status', 'created_at'], unique=False, schema='linguamentor', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'escalated'::character varying])::text[]))")
    op.alter_column('score_appeals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_refresh_tokens_hash'), 'refresh_tokens', ['token_hash'], unique=False, schema='linguamentor', postgresql_where='(revoked_at IS NULL)')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_rs_created_brin'), 'readiness_snapshots', ['created_at'], unique=False, schema='linguamentor', postgresql_with={'pages_per_range': '64'}, postgresql_using='brin')
    op.create_index(op.f('idx_readiness_snapshots_user_time'), 'readiness_snapshots', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('readiness_snapshots', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_lp_target_language'), 'learner_profiles', ['target_language'], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_lp_target_exam'), 'learner_profiles', ['target_exam'], unique=False, schema='linguamentor', postgresql_where='(target_exam IS NOT NULL)')
    op.create_index(op.f('idx_lp_cefr_writing_user'), 'learner_profiles', ['cefr_writing', 'user_id'], unique=False, schema='linguamentor', postgresql_where='(cefr_writing IS NOT NULL)')
    op.create_index(op.f('idx_lp_accent_target'), 'learner_profiles', ['accent_target'], unique=False, schema='linguamentor')
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('learner_profiles', 'placement_completed_at', schema='linguamentor')
    op.create_index(op.f('idx_exam_sections_attempt'), 'exam_sections', ['exam_attempt_id'], unique=False, schema='linguamentor')
    op.alter_column('exam_sections', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.create_index(op.f('idx_exam_attempts_user_id'), 'exam_attempts', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('exam_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_constraint('uq_daily_sessions_user_date', 'daily_sessions', schema='linguamentor', type_='unique')
    op.create_index(op.f('idx_ds_session_date_completed'), 'daily_sessions', ['session_date', 'completed'], unique=False, schema='linguamentor', postgresql_where='(completed = false)')
    op.create_index(op.f('idx_daily_sessions_user_date'), 'daily_sessions', ['user_id', sa.literal_column('session_date DESC')], unique=False, schema='linguamentor')
    op.create_unique_constraint(op.f('daily_sessions_user_id_session_date_key'), 'daily_sessions', ['user_id', 'session_date'], schema='linguamentor', postgresql_nulls_not_distinct=False)
    op.alter_column('daily_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('daily_sessions', 'srs_priority_score', schema='linguamentor')
    op.create_index(op.f('idx_amr_user_ref_task_created'), 'ai_model_runs', ['user_reference_id', 'task_type', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(user_reference_id IS NOT NULL)')
    op.create_index(op.f('idx_amr_provider_task_created'), 'ai_model_runs', ['provider_name', 'task_type', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(provider_name IS NOT NULL)')
    op.create_index(op.f('idx_amr_model_name_created'), 'ai_model_runs', ['model_name', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.create_index(op.f('idx_amr_created_brin'), 'ai_model_runs', ['created_at'], unique=False, schema='linguamentor', postgresql_with={'pages_per_range': '128'}, postgresql_using='brin')
    op.create_index(op.f('idx_amr_calibration_version_created'), 'ai_model_runs', ['calibration_version', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor', postgresql_where='(calibration_version IS NOT NULL)')
    op.create_index(op.f('idx_ai_model_runs_task_time'), 'ai_model_runs', ['task_type', sa.literal_column('created_at DESC')], unique=False, schema='linguamentor')
    op.alter_column('ai_model_runs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='linguamentor')
    op.drop_column('ai_model_runs', 'calibration_sample_count', schema='linguamentor')
    # ### end Alembic commands ###
